version: '3'

services:

  account-service:
    build:
      context: ./../account-service
      dockerfile: ./../account-service/account-service.dockerfile
    restart: always
    ports:
      - "8000:80"
    deploy:
      mode: replicated
      replicas: 1
      
  chat-service:
    build:
      context: ./../chat-service
      dockerfile: ./../chat-service/chat-service.dockerfile
    restart: always
    ports:
      - "8001:80"
    deploy:
      mode: replicated
      replicas: 1

  stream-service:
    build:
      context: ./../stream-service
      dockerfile: ./../stream-service/stream-service.dockerfile
    restart: always
    ports:
      - "8002:80"
    deploy:
      mode: replicated
      replicas: 1
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password 
      MYSQL_DATABASE: usersdb
      MYSQL_USER: hiendv
      MYSQL_PASSWORD: password
  redis-app:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass password
   